DOC: improving auth section
- Made it clearer that the dev needs to also create the `.env` folder, not just update the `allowed_origins`, as without the `.env` folder the site threw a `500` error when trying to check a word. Not sure if this is a feature or a bug.
```bash
File "api.py", line 69, in checkHeaders
    tokens = json.loads(os.getenv('TOKEN_KEYS')) #this will throw an error upon request if no token keys are present in the environment at all
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```
- Included a Note under configuration explaining what errors might arise if authorisation hasn't been set up properly.
- Made ` Making Request with Authorization Tokens` a level 2 header to differentiate it from `Running locally`.
- Added more information to 'Making Request with Authorization Tokens'